document.addEventListener('DOMContentLoaded',function(){const themeToggle=document.getElementById('theme-toggle');const mobileThemeToggle=document.getElementById('mobile-theme-toggle');const body=document.body;const html=document.documentElement;const savedTheme=localStorage.getItem('theme');if(savedTheme==='dark'){enableDarkMode()}else if(savedTheme==='light'){disableDarkMode()}else{if(window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches){enableDarkMode()}}
if(themeToggle){themeToggle.addEventListener('click',toggleTheme)}
if(mobileThemeToggle){mobileThemeToggle.addEventListener('click',toggleTheme)}
function toggleTheme(){if(body.classList.contains('dark-mode')){enableDarkMode()}else{disableDarkMode()}
body.classList.add('theme-transition');setTimeout(()=>{body.classList.remove('theme-transition')},1000);createThemeToggleEffect(event)}
function enableDarkMode(){body.classList.add('dark-mode');html.classList.add('dark');localStorage.setItem('theme','dark');updateThemeButtonText('light');updateVisualElements('dark')}
function disableDarkMode(){body.classList.remove('dark-mode');html.classList.remove('dark');localStorage.setItem('theme','light');updateThemeButtonText('dark');updateVisualElements('light')}
function updateThemeButtonText(mode){const currentLang=document.documentElement.lang||'ar';const themeText=currentLang==='ar'?(mode==='dark'?'وضع الليل':'وضع النهار'):(mode==='dark'?'Dark Mode':'Light Mode');const themeIcon=mode==='dark'?'fa-moon':'fa-sun';if(themeToggle){const textSpan=themeToggle.querySelector('span');const icon=themeToggle.querySelector('i');if(textSpan)textSpan.textContent=themeText;if(icon){icon.className='';icon.classList.add('fas',themeIcon)}}
if(mobileThemeToggle){const textSpan=mobileThemeToggle.querySelector('span');const icon=mobileThemeToggle.querySelector('i');if(textSpan)textSpan.textContent=themeText;if(icon){icon.className='';icon.classList.add('fas',themeIcon)}}}
function updateVisualElements(mode){const stars=document.querySelectorAll('.star');stars.forEach(star=>{if(mode==='dark'){star.style.boxShadow='0 0 4px var(--space-accent-2)'}else{star.style.boxShadow='none'}});const planets=document.querySelectorAll('.planet-effect');planets.forEach(planet=>{if(mode==='dark'){planet.classList.add('dark-planet')}else{planet.classList.remove('dark-planet')}})}
function createThemeToggleEffect(event){const toggleButton=event.currentTarget;const rect=toggleButton.getBoundingClientRect();const x=rect.left+rect.width/2;const y=rect.top+rect.height/2;const starburst=document.createElement('div');starburst.classList.add('theme-toggle-effect');starburst.style.left=`${x}px`;starburst.style.top=`${y}px`;document.body.appendChild(starburst);setTimeout(()=>{starburst.remove()},1500)}
if(window.matchMedia){window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change',e=>{if(e.matches){enableDarkMode()}else{disableDarkMode()}})}})