function initLibraries(){if(typeof AOS!=='undefined'){AOS.init({duration:800,easing:'ease-in-out',once:!1})}}
function updateCopyrightYear(){const yearElement=document.getElementById('current-year');if(yearElement){yearElement.textContent=new Date().getFullYear()}}
function setupContactForm(){const contactForm=document.getElementById('contact-form');if(!contactForm)return;const elements={form:contactForm,submitButton:contactForm.querySelector('button[type="submit"]'),successMessage:document.getElementById('success-message'),errorMessage:document.getElementById('error-message'),fields:{name:document.getElementById('name'),email:document.getElementById('email'),subject:document.getElementById('subject'),message:document.getElementById('message')}};elements.form.addEventListener('submit',handleSubmit);Object.values(elements.fields).forEach(field=>{if(field){field.addEventListener('input',()=>clearError(field))}})}
function handleSubmit(e){e.preventDefault();const form=e.target;console.log(form);const submitButton=form.querySelector('button[type="submit"]');const originalText=submitButton.innerHTML;if(!validateForm(form))return;submitButton.disabled=!0;submitButton.innerHTML='<i class="mr-2 fas fa-spinner fa-spin"></i>جاري الإرسال...';sendFormData(form).then(()=>{showSuccess();form.reset()}).catch(error=>{showError(error)}).finally(()=>{submitButton.disabled=!1;submitButton.innerHTML=originalText})}
function validateForm(form){let isValid=!0;const fields={name:form.querySelector('#name'),email:form.querySelector('#email'),subject:form.querySelector('#subject'),message:form.querySelector('#message')};if(!fields.name.value.trim()){showError(fields.name,'الاسم مطلوب');isValid=!1}
if(!fields.email.value.trim()){showError(fields.email,'البريد الإلكتروني مطلوب');isValid=!1}else if(!isValidEmail(fields.email.value)){showError(fields.email,'بريد إلكتروني غير صالح');isValid=!1}
if(!fields.subject.value.trim()){showError(fields.subject,'الموضوع مطلوب');isValid=!1}
if(!fields.message.value.trim()){showError(fields.message,'الرسالة مطلوبة');isValid=!1}
return isValid}
async function sendFormData(form){form.insertAdjacentHTML('beforeend',`
    <input type="hidden" name="_captcha" value="false">
    <input type="hidden" name="_template" value="table">
    <input type="hidden" name="_next" value="https://portfolio-tlnz.vercel.app">
  `);if(typeof emailjs!=='undefined'){await emailjs.sendForm('service_w5aymqc','template_bvxoe5q',form)}else{throw new Error('EmailJS غير محمل')}}
function isValidEmail(email){return/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)}
function showError(input,message){const formGroup=input.parentElement;let errorElement=formGroup.querySelector('.error-message');input.classList.add('invalid');input.classList.remove('valid');if(!errorElement){errorElement=document.createElement('div');errorElement.className='error-message';formGroup.appendChild(errorElement)}
errorElement.textContent=message}
function clearError(input){const formGroup=input.parentElement;const errorElement=formGroup.querySelector('.error-message');if(errorElement){errorElement.remove()}
input.classList.remove('invalid');input.classList.add('valid')}
function showSuccess(){const successMessage=document.getElementById('success-message');if(successMessage){successMessage.style.display='block';setTimeout(()=>{successMessage.style.display='none'},5000);createSuccessEffect()}}
function createSuccessEffect(){for(let i=0;i<5;i++){setTimeout(()=>{const starburst=document.createElement('div');starburst.className='starburst-effect';starburst.style.left=`${Math.random() * window.innerWidth}px`;starburst.style.top=`${Math.random() * (window.innerHeight / 2) + window.innerHeight / 4}px`;document.body.appendChild(starburst);setTimeout(()=>starburst.remove(),1000)},i*200)}}
function setupSmoothScrolling(){const scrollToTopButton=document.getElementById('scroll-to-top');window.addEventListener('scroll',function(){if(window.scrollY>300){scrollToTopButton.classList.remove('opacity-0','invisible');scrollToTopButton.classList.add('opacity-100','visible')}else{scrollToTopButton.classList.remove('opacity-100','visible');scrollToTopButton.classList.add('opacity-0','invisible')}});scrollToTopButton.addEventListener('click',function(){window.scrollTo({top:0,behavior:'smooth'})});document.querySelectorAll('a[href^="#"]').forEach(anchor=>{anchor.addEventListener('click',function(e){e.preventDefault();const target=document.querySelector(this.getAttribute('href'));if(target){window.scrollTo({top:target.offsetTop-80,behavior:'smooth'})}})})}
document.addEventListener('DOMContentLoaded',()=>{setupSmoothScrolling();initLibraries();updateCopyrightYear();setupContactForm()})